[package]
description = "Create, share, fetch and model linked Atomic Data!"
license = "MIT"
name = "atomic"
repository = "https://github.com/atomicdata-dev/atomic-server"
version = "0.15.0"

[[module]]
abi = "wasi"
name = "atomic"
source = "../target/wasm32-wasi/release/atomic-cli.wasm"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
module = "atomic-cli.wasm"
name = "atomic"
